# 学习前的准备
## 机器学习初认识
1. 定义：从数据中总结规律的统计方法。
2. 组成：各种用于总结规律并进行预测或分类的模型（算法）。
3. 地位：包含**神经网络模型**和**深度学习**等方法。
* **神经网络模型**：使用多个神经元（神经细胞模型）的方法
* **深度学习**：在多个层使用大量神经元的方法。
4. 学习窍门：
   * 假设维度D为2；
   * 编写程序；
5. **问题分类**：
   * 有监督学习；
     >对于输入给出相应的输出
   * 无监督学习；
     >发现输入数据的规律
   * 强化学习；
     >找出使最后结果（整体结果）达到最优的动作

## Python前置知识复习
### 基本语法
#### 1. 四则运算：就正常输入
例如：


In [2]:
(1+2+3+5)/5

2.2

#### 2. **幂运算**：用**表示

In [3]:
2**8

256

#### 3. 变量：字母数字下划线，不能以数字开头，大小写敏感
#### 4. **类型**：  
int(整数),float(实数),str,bool,list(列表,shuzu ),tuple(元组、数组，元素不可修改),ndarray(矩阵,eg.a=np.array([1,2,3]))  
* **检查类型**：type()

In [6]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


#### 5. **print语句**：print()
字符串格式化：
* "%占位符" % 变量
* 语法：f"内容{变量}"
   -- 不限制数据类型，也不做精度控制

In [ ]:
'''
 - 占位型拼接 
  %s  (%:占位 s:将内容转换成字符串，放到占位的地方)  
  %d  (%:占位 d:将内容转换成整数，放到占位的地方)  
  %f  (%:占位 f:将内容转换成a浮点型，放到占位的地方)  
    -- 控制精度：(m.n) --%m,%m.n,%.n都可以单独出现
    -- m：控制宽度，要求是数字（很少使用），设置的宽度小于自身，不生效
    -- .n：控制小数点精度，要求是数字，会进行小数的四舍五入
    -- %5d:数字宽度控制在5位，不够的前面补够空格
    -- %5.2f:宽度控制为5，小数点精度设置为2(这种时候会四舍五入)
   -- e.g name = "Delta"
          print("hello,I am %s" % name)
   -- 多个变量占位，变量要用括号括起来，并且按照占位的顺序填入
'''
name = "Delta"
print("hello,I am %s" % name)

# 将数字都换成字符串来拼接
birth_month = 10
avg_salary = 20000
message = "我出生在%s月，现在平均工资为每月：%s 元" %(birth_month,avg_salary)
print(message)
# 各自用各自的占位方式来完成拼接,同时进行精度控制
name_self = "Delta"
birth_month = 9
avg_salary = 20000.1314
message = "我叫%s,我出生在%2d月，现在平均工资为每月：%.2f 元" %(name_self,birth_month,avg_salary)
print(message)
# 快速格式化
name_self = "Delta"
birth_month = 9
avg_salary = 20000.1314
message = f"我叫{name_self},我出生在{birth_month}月，现在平均工资为每月：{avg_salary} 元"
print(message)

hello,I am Delta
我出生在10月，现在平均工资为每月：20000 元
我叫Delta,我出生在 9月，现在平均工资为每月：20000.13 元
我叫Delta,我出生在9月，现在平均工资为每月：20000.1314 元


#### 6. **list**、**tuple**:  均可用来表示数组
* list[],tuple();  
* list里的元素也可以是list,查询时list[i][j]就OK;  
* tuple中的元素不能改变

**创建连续的整数数组**：range()  
* range中的元素同样不可修改；  
* 起始数字省略则默认是从0开始；  
* 末尾的数字是期望数字+1；

In [2]:
y = range(5,10)
i=0
while i < len(y):
    print(y[i])
    i += 1


5
6
7
8
9


#### 7. **for、while**
#### 8. **if**
#### 9. **向量**
* **NumPy**：表示向量和矩阵时需要导入此库

In [ ]:
import numpy as np
# 定义向量
x = np.array([1,2])
x
# print(x) # 执行这句则不会出现array([1,2])，而会直接输出[1 2];

array([1, 2])

In [12]:
import numpy as np
x = np.array([1,2])
y = np.array([3,4])
print(x+y)
print(type(x))
print(x[1]) # 读取元素
x[0] = 100 # 替换元素
print(x)

[4 6]
<class 'numpy.ndarray'>
2
[100   2]


**创建连续整数的向量**：np.arange(n),元素递增的向量数组

In [13]:
import numpy as np
x = np.arange(10)
print(x)
print(type(x))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


**ndarray类型可以进行向量计算，list不可以**

In [15]:
import numpy as np
x = np.array([1,2])
y = np.array([3,4])
print(x+y)

print([1,2]+[3,4])

[4 6]
[1, 2, 3, 4]


复制ndarray类型的数据时，不可以简单地a=b,而要**a=b.copy()**  
* a=b,会导致后面b改变时,a也跟着变  
* 而.copy()就不会这样

In [16]:
import numpy as np
x = np.array([1,2])
y = np.array([3,4])
a = x
b = y.copy()
print(a)
print(b)
x[0] = 20
print(a)
print(b)

[1 2]
[3 4]
[20  2]
[3 4]


#### 10. **矩阵**
* 定义 np.array([[...],[...]]) --**很明显可以看出是list类型-[]**
* 大小 .shape
* 读取 x[i,j]
* 替换 x[i,j] = a
* 生成元素为0或1的矩阵：np.zeros(size);np.ones(size),**size为tuple型,用括号括起**
* 生成元素随机的矩阵 np.random.rand(size)
* 改变矩阵的大小 a = a.reshape(i,j) i*j的矩阵

In [3]:
import numpy as np
x = np.array([[1,2,3],[4,5,6]])
print(x)
print(x.shape) # 大小
print(x[0,2])
x[0][2] = 1 # 修改元素
print(x)
y = np.zeros(10) # 10个0
y_12 = np.zeros((2,10)) # 2*10个0
z = np.ones((2,10))
print(y)
print(y_12)
print(z)
J = np.random.rand(10) # 生成元素随机的矩阵
print(J)
z = z.reshape(4,5) # 改变矩阵大小
print(z)


[[1 2 3]
 [4 5 6]]
(2, 3)
3
[[1 2 1]
 [4 5 6]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[0.97579801 0.87311772 0.05761227 0.11036067 0.26158287 0.44664679
 0.85654807 0.64851895 0.11548921 0.3006237 ]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


#### 11.矩阵的四则运算
1. +、-：正常
2. **标量*矩阵**：矩阵中的所有元素都会受到影响

In [22]:
import numpy as np
x = np.array([[1,2,3],[4,5,6]])
print(10*x)

[[10 20 30]
 [40 50 60]]


3. **算数函数**：
* np.sqrt(x): 平方根
* np.exp(x): 指数函数
* np.log(x): 对数函数
* np.round(x,小数点后的位数): 四舍五入
* np.mean(x): 均值函数
* np.std(x): 标准差函数
* np.max(x),np.min(x): 最值
4. **矩阵乘积**：矩阵v,w的乘积：v.dot(w)

In [23]:
import numpy as np
x = np.array([[4,4,4],[9,9,9]])
print(np.sqrt(x))

[[2. 2. 2.]
 [3. 3. 3.]]


In [24]:
x = np.array([1,2])
y = np.array([3,4])
print(x.dot(y))

11


#### 12. 切片
list和ndarray类型都具有此功能，可以**将元素的一部分汇总起来表示**  
表示方法：“**：**”
* 例如：
   * **变量名[:n]**--一次性读取0~n-1的元素
   * **变量名[n:]**--读取从n到末尾的元素
   * **变量名[n1:n2]**--读取读取n1~n2-1的元素
   * **变量名[n1:n2:dn]**--每隔dn从n1~n2-1读取一个元素
   * **变量名[::-1]**--实现逆序读取
   * 还适用于一维以上的ndarray类型

In [8]:
import numpy as np
x = np.random.rand(10)
print(x)
print(x[:8])
print(x[2:])
print(x[1:7])
print(x[2:8:2])
print(x[::-1])
z = np.array([[1,2,3,4,5],[0,9,8,7,6]])
print(z[:2,1:3])

[0.83884472 0.92452701 0.58492357 0.17040238 0.87288188 0.14244074
 0.24062303 0.63380647 0.28301636 0.69236226]
[0.83884472 0.92452701 0.58492357 0.17040238 0.87288188 0.14244074
 0.24062303 0.63380647]
[0.58492357 0.17040238 0.87288188 0.14244074 0.24062303 0.63380647
 0.28301636 0.69236226]
[0.92452701 0.58492357 0.17040238 0.87288188 0.14244074 0.24062303]
[0.58492357 0.87288188 0.24062303]
[0.69236226 0.28301636 0.63380647 0.24062303 0.14244074 0.87288188
 0.17040238 0.58492357 0.92452701 0.83884472]
[[2 3]
 [9 8]]


#### 13. 替换满足条件的数据-**bool数组**


In [9]:
import numpy as np
x = np.array([1,1,2,3,5,8,13])
x>3

array([False, False, False, False,  True,  True,  True])

In [10]:
x[x>3]

array([ 5,  8, 13])

In [11]:
x[x>3] = 999
print(x)

[  1   1   2   3 999 999 999]


#### 14. help
**help(函数名)**：可以将该函数的说明文件显示出来

In [12]:
import numpy as np
help(np.random.randint)

Help on method randint in module numpy.random:

randint(low, high=None, size=None, dtype=<class 'int'>) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)

    Return random integers from `low` (inclusive) to `high` (exclusive).

    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).

    .. note::
        New code should use the `~numpy.random.Generator.integers`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.

    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, o

#### 15. 函数

#### 16. 保存文件
* 保存一个ndarray类型变量
   * 保存：**np.save('文件名.npy',变量名)** --文件后缀名:**.npy**
   * 读取：**np.load('文件名.npy')**

In [13]:
data = np.array([1,1,2,3,5,8,13])
print(data)

np.save('datafile.npy',data) # 保存文件
data = []  # 清空数据
print(data)

data = np.load('datafile.npy') # 读取文件
print(data)

[ 1  1  2  3  5  8 13]
[]
[ 1  1  2  3  5  8 13]


* 保存多个ndarray类型变量
  * 保存：**np.savez('文件.npz',变量名1=变量名1,变量名2=变量名2,...)** --文件后缀名:**.npy**
  * 读取：**np.load('文件名.npz')**

In [16]:
data1 = np.array([1,2,3])
data2 = np.array([10,20,30])
np.savez('datafile2.npz',data1=data1,data2=data2) # 保存文件
data1 = []
data2 = []
outfile = np.load('datafile2.npz') # 读取文件
print(outfile.files) # 显示存储的所有数据
data1 = outfile['data1'] # 取出data1
data2 = outfile['data2'] # 取出data2
print(data1)
print(data2)

['data1', 'data2']
[1 2 3]
[10 20 30]
